import axios from "axios";

const instance = axios.create({
  baseURL: "http://sikapapi.sundareka.com",
  headers: {
    Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjcxMjg0ODEsImlhdCI6MTYyNzA0MjA4MSwiaXNzIjoiYWRtaW5AYWRtaW4uY29tIiwic3ViIjoiYWNjZXNzX3Rva2VuIiwiSUQiOjAsIkRhdGEiOnsidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJTdXBlciBBZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmUiOiIwODIyNDA0NTA3MDIxIiwicm9sZV9pZCI6MSwidHRkX3VybCI6IiIsInBpY3R1cmVfdXJsIjoiL3N0YXRpYy9pbWFnZXMvcHJvcGljYWRtaW5AYWRtaW4uY29tLnBuZyIsInN0YXR1cyI6dHJ1ZSwibm9payI6IjEyNzI2NjYiLCJub2lwIjoiOTgyNjYyIiwia2V0ZXJhbmdhbiI6IiIsIm90cCI6IiIsImRpcmVrdG9yYXRfaWQiOjAsInJvbGUiOnsiaWQiOjEsIm5hbWUiOiJTVSIsInBlcm1pc3Npb25zIjpbXX0sImRpcmVrdG9yYXQiOnsiaWQiOjAsInBhcmVudF9pZCI6MCwibmFtYV9kaXJla3RvcmF0IjoiIiwibGV2ZWwiOjB9fX0.CzBW7x1YJ0-LMqzGxaypQ-NrHZJryVAKGwYmKY_RQIw`,
  },
});
export default instance;
